global:
  scrape_interval: '5s'
  evaluation_interval: '5s'

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets:
        - 'node_exporter:9100'
        labels:
          instance: 'instance-1'

scrape_configs:
  - job_name: 'blog' 
    metrics_path: '/prometheus'
    static_configs:
        - targets: 
            - '192.168.0.155:8080'