{
 "title": "Java Spring Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total success",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_requests_success{handler=\"HomeController.endpointA\",instance=\"192.168.0.155:8080\",job=\"blog\",method=\"GET\",status=\"200\"}"
    }
   ]
  },
  {
   "title": "Total Failure",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "http_requests_error{handler=\"HomeController.endpointB\",instance=\"192.168.0.155:8080\",job=\"blog\",method=\"GET\",status=\"404\"}"
    }
   ]
  },
  {
   "title": "JavaSpringMonitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"blog\", handler=\"HomeController.endpointA\"}[60s])"
    },
    {
     "expr": "rate(http_requests_total{job=\"blog\", handler=\"HomeController.endpointB\"}[60s])"
    }
   ]
  }
 ]
}